Update Conan.cmake to fix #40
cpp-best-practices/cpp_starter_project pull request #122
Opened 2021-02-27 19:18 UTC by Domkeykong

This fixes #40 when building using an alternate compiler like `clang`.

2021-11-12 11:10 UTC, LtdSauce commented
I can confirm that i still experienced the issue that this PR tries to solve with latest main branch. (Although i wasn't asked)

2021-11-14 19:40 UTC, c60cb859 commented
> I can confirm that i still experienced the issue that this PR tries to solve with latest main branch. (Although i wasn't asked)

+1 from me. Running on Linux

2021-11-30 01:42 UTC, ddalcino commented
> > I can confirm that i still experienced the issue that this PR tries to solve with latest main branch. (Although i wasn't asked)
> 
> +1 from me. Running on Linux

Me too: see https://github.com/cpp-best-practices/cpp_starter_project/pull/175#discussion_r758840060. This PR resolved the issue for me. I must note that this was a very specific situation: [CLion + CMakePresets + Linux + clang}; if I change any one of these variables to anything else, I do not experience the problem.

2021-11-30 01:46 UTC, ddalcino requested changes
Please merge upstream/main into this branch, and resolve the merge conflict. Note that `conan_cmake_run` has turned into `conan_cmake_install`, but the `ENV` argument that this PR adds is still a valid argument for `conan_cmake_install`.

2021-11-30 18:44 UTC, ddalcino commented
When #169 is merged, this PR will have less relevance here because the Conan.cmake file will be moved into [ProjectOptions](https://github.com/aminya/ProjectOptions).

@aminya, I think this change is worth adding to ProjectOptions. Several of our users have found this change useful, including myself (see above). I don't think that there is any downside to adding this: there should never be a situation where you would want Conan to use a different compiler than the one used by the project. What do you think?

You could argue that this change is only relevant when the user has failed to set CC and CXX manually, and that not setting these environment variables yourself is "user error". I prefer to forgive users for that "mistake", if it is one, particularly since this change won't hurt anything.

This is how I would expect Conan.cmake in ProjectOptions to be changed:
```diff
    conan_cmake_install(
      PATH_OR_REFERENCE ${CMAKE_SOURCE_DIR}
      BUILD missing
            # Pass compile-time configured options into conan
      OPTIONS ${ProjectOptions_CONAN_OPTIONS}
+     ENV "CC=${CMAKE_C_COMPILER}" "CXX=${CMAKE_CXX_COMPILER}"
      SETTINGS ${settings})
```
I can file a PR for this myself, but I want to give @Domkeykong a chance to do it; it's @Domkeykong's PR, not mine.

2021-12-04 03:33 UTC, closed without merging

2021-12-04 03:35 UTC, aminya commented
This is included in ProjectOptions v0.11.2
https://github.com/aminya/ProjectOptions