Fix coverage reporting
cpp-best-practices/cpp_starter_project pull request #191
Opened 2022-02-06 15:49 UTC by lefticus

* Need to make sure opt_enable_coverage is set when appropriate (only for Debug builds, since it overrides optimization settings)
 * Remove explicit sources dir from windows coverage, so that it still works when template project is used
 * Make sure gcov version/executable is set correctly
 * Add simple test of main executable, to show its coverage also

Note: these issues were discovered while using a recent project made from the template. I think most of these issues are long standing. Previously `ENABLE_COVERAGE` was enabled by default, so it happened to work, but Release builds were not doing what we thought they were doing.

2022-02-06 20:37 UTC, aminya requested changes

2022-02-06 20:37 UTC, aminya commented on .github/workflows/ci.yml
> +            gcov: gcov
Should we choose a better name for this variable? I am afraid it is confused with the gcovr input passed to setup-cpp

2022-02-06 20:39 UTC, aminya commented on test/CMakeLists.txt
> +add_test(NAME cli.has_help COMMAND intro --help)
A description for this test would be useful

2022-02-07 00:22 UTC, aminya approved these changes

2022-02-07 05:23 UTC, ddalcino approved these changes

2022-02-07 05:39 UTC, merged